language: node_js
node_js:
  - "4"
  - "6"
  - "node"

branches:
  only:
    - /^\d+\.\d+\.\d+$/

install:
  - npm install

script:
  - npm test

before_deploy: |
  if [ -z "$GITHUB_API_KEY" ]; then
    echo "No GITHUB_API_KEY given ! Deployment skipped"
    exit 0
  fi

deploy:
  on:
    tags: true
  - VERSION=`node -e "console.log(require('./package.json').version);"`
  - if [ $TRAVIS_TAG != $VERSION ]; then echo "Git Tag and package version mismatch" ; fi
 